### ISSUE TITLE
Add new video and audio features

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#11]
Some new video and audio features that could be implemented:

- [x] Screenshot command should accept `pts` as argument
- [x] Add a new command to extract the entire audio from a video. It could be something like this `save-audio-sample --start=0 --end=maxpts`

**Comment by rr-** [comment]
The last two checkboxes aren't wel ldefined, plus these should go as separate tickets so that the possible discussion can be limited only to relevant places.

**Comment by Luni-4** [comment]
Opened a new issue for zoom. Thanks!

**Comment by rr-** [comment]
For now implemented the screenshots:

c834b65f96527eb0aa8b89db7dcdc631c03a2a6d
ec3e53bf110275927eece3615c5f0eaf1c122f86

**Comment by rr-** [comment]
Added exporting whole audio:

https://github.com/rr-/bubblesub/commit/21ca33d3ab34db1076ccb8b86365cf555a7c82c0
https://github.com/rr-/bubblesub/commit/b621f8b56692623c7f41ace5c73fa5a129c0b8c8
https://github.com/rr-/bubblesub/commit/e3a4f61f4759cab6b1efc70422d7dd8159cbcba5
