### ISSUE TITLE
Implement zoom

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#12]
Implement zoom in/out for the loaded video. A possible implementation could be scrolling on the video widget with mouse wheel with or without holding `ctrl`.

**Comment by rr-** [comment]
What about dragging? Do you want any buttons? How is Aegisub handling it?

**Comment by Luni-4** [comment]
I found dragging pretty uncomfortable.
No buttons, please.
Aegisub uses a select box. From 12.5% to 300%.

**Comment by rr-** [comment]
Got it

**Comment by Luni-4** [comment]
Sure! Thanks!

**Comment by rr-** [comment]
Implemented in

- 4274ab6 2019-02-14 api+cmd: add video zoom                            [rr- <rr-@sakuya.pl>]* 93fa5e9 2019-02-14 ui: make wheel zoom the video                      [rr- <rr-@sakuya.pl>]
* 1219207 2019-02-14 ui/menu: add video zoom commands                   [rr- <rr-@sakuya.pl>] (HEAD -> master, origin/master)
