### ISSUE TITLE
Improve menu look on dark theme

### ISSUE THREAD

**Issue by rr-** [rr-/bubblesub#13]
Separators are almost invisible.
Disabled menu entries aren't well visible, too.

**Comment by rr-** [comment]
Unfortunately my hands are tied as both of these aspects depend on the current Qt scheme implementation, and I'd rather avoid forcing bubblesub to be tied to one or two Qt themes.

You can use following plugin to remove shadows from disabled text in the menus:

```python
from PyQt5 import QtWidgets

from bubblesub.api import Api


class CustomStyle(QtWidgets.QProxyStyle):
    def styleHint(
        self,
        hint: int,
        option: QtWidgets.QStyleOption = 0,
        widget: QtWidgets.QWidget = 0,
        returnData: QtWidgets.QStyleHintReturn = 0,
    ) -> int:
        if not QtWidgets:
            return 0
        if hint == QtWidgets.QStyle.SH_UnderlineShortcut:
            return 0
        if hint == QtWidgets.QStyle.SH_EtchDisabledText:
            return 0
        return super().styleHint(hint, option, widget, returnData)


def on_load(api: Api) -> None:
    QtWidgets.QApplication.setStyle(CustomStyle())
```

I also made it remove the accelerators which you seem to dislike.

**Comment by Luni-4** [comment]
That's great! Thanks! 
I think I'm gonna change the menu separator's color also.

**Comment by Luni-4** [comment]
As we discussed on IRC, it would be great adding stylesheet support to the palettes, so on top of the color palette one could add some user stylesheet.

**Comment by rr-** [comment]
- 3a3ae48 `ui: change palettes to themes`
- b4a90e7 `ui: add ability for themes to change stylesheet`
- 7fc63e3 `ui: improve dark theme menus`

![asd](https://user-images.githubusercontent.com/1045476/52911934-b3918b80-32aa-11e9-9f75-8318d6c82e42.png)
