### ISSUE TITLE
Unfocusing time edit leaves invalid state

### ISSUE THREAD

**Issue by rr-** [rr-/bubblesub#16]
When `TimeEdit` is initialized for the first time, it properly displays `00:00:00` thanks to the (rather roundabout) call to the `reset_text` method.

But after the user selects and deselects a subtitle on the subtitle grid, `ImmediateDataWidgetMapper` calls `setText` rather than `set_value` causing the widget to contain `: : .`.

**Comment by rr-** [comment]
@Luni-4 LMK if 124d74d224b9f80a7186a4da0f040cde02a48109 fixes this behavior for you

**Comment by Luni-4** [comment]
It works perfectly, thanks! You can close this one!
