### ISSUE TITLE
Can't save or open any dialog if the video is unpaused

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#21]
I want to point out that all instances of `QDialog` and `QMessageBox` are affected. Below I present some libraries and system info that I'm using right now. 

- `PyQt5  5.11.3`

- `Python 3.7.1`

- `mpv f2e7e81 `

- `quamash 1.2.0`

- `ffms2 2d3b4fa`

- `Ubuntu Cosmic 18.10`

**Comment by rr-** [comment]
Fixed:

- 756b044 `ui: shorten async dialog code`
- 077a916 `ui: make all dialogs use the main event loop`
- 1d124ee `ui: ensure every dialog has a parent widget`
- 647e513 `ui: pause video when showing modal dialogs`
