### ISSUE TITLE
Strange focus on dragging

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#22]
Dragging `QMessageBox` around changes the focus from `Close without Saving ` to the `Save` button. When dragging is stopped, the focus returns on the `Close without Saving ` button.

**Comment by rr-** [comment]
I think it's Qt / window manager thing, bubblesub certainly doesn't meddle with button focus in the dialogs.

**Comment by rr-** [comment]
Fixed in 2590104ccd46d3e7e2554a760dae3d2dec355544
