### ISSUE TITLE
AttributeError: module 'xdg' has no attribute 'XDG_CACHE_HOME'

### ISSUE THREAD

**Issue by Subarashii-no-Fansub** [rr-/bubblesub#40]
Hello,

I have constantly this kind of error: `AttributeError: module 'xdg' has no attribute 'XDG_CACHE_HOME'`

In the case this attribute is not set, maybe you should add a fallback to $HOME/.local/share/

Thanks for bubblesub

**Comment by rr-** [comment]
That's weird, can I see your `pip freeze`?

**Comment by Subarashii-no-Fansub** [comment]
After a check of my `pip freeze`, it seems `pyxdg==0.26` and `xdg==4.0.0` were in conflict.

pyxdg == python2-pyxdg, a dependency required by blender.

**Comment by rr-** [comment]
Thanks. Since I had removed the dependency on the newest master and there are no versions released yet outside of git master, I'm closing the ticket.
