### ISSUE TITLE
Make pyenchant optional

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#43]
`pyenchant` should be replaced by another spelling library. 

The following one could be a valid alternative: [pyspellchecker](https://github.com/barrust/pyspellchecker)

**Comment by rr-** [comment]
We still might support enchant but optionally. This file laid a good foundation for swappable spell checking here: https://github.com/rr-/bubblesub/blob/master/bubblesub/spell_check.py#L63

**Comment by Luni-4** [comment]
> We still might support enchant but optionally. This file laid a good foundation for swappable spell checking here: https://github.com/rr-/bubblesub/blob/master/bubblesub/spell_check.py#L63

I agree, but I would set `pyenchant` as a second choice, because of the difficulties in finding the `enchant` binaries for Windows.

**Comment by rr-** [comment]
5d66514776b455788b2305c74bcf82b049c24561
ef14c898a56641ff6a2ea7d7cc764684591d0147
bcae48a58e9037118df96f4055d4bafebad1b9d2

**Comment by Luni-4** [comment]
It works! Thanks! 

It doesn't find the `en` dictionary though, but it's not related to this issue.
