### ISSUE TITLE
Widgets disappears when splitters are moved

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#45]
This problem affects a non-maximized main window.

If the video splitter is moved to the left till the main window boundaries, volume slider and play/pause buttons disappear completely. The same happens with the notes fields if the splitter is moved to the right.

![image](https://user-images.githubusercontent.com/12353765/59457280-6cf70c80-8e18-11e9-9c1a-90faa018c511.png)

**Comment by Luni-4** [comment]
Things are getting strange. I've figured out that the bug is related to margins, in fact, if I change the 84 line of `main_window.py` from

`self.main_splitter.setContentsMargins(8, 8, 8, 8)`

to

`self.main_splitter.setContentsMargins(2, 2, 2, 2)`

the issue is fixed for the dark theme, but not for the light one. I don't know what it could be sincerely...

**Comment by rr-** [comment]
Can't reproduce:

https://0x0.st/z2ss.webm

**Comment by Luni-4** [comment]
> Can't reproduce:
> 
> https://0x0.st/z2ss.webm

From the video I can't see it clearly, was the window non-maximized? Because a fullscreen window works perfectly for me with any theme.

Could the problem be related to the size of the `main_window` on the opening of `bubblesub`? Perhaps it should be increased a bit.

I confirm that if I comment the 84 line of `main_window.py `, the issue is fixed.

**Comment by rr-** [comment]
Yes, it was windowed.  This is weird.

**Comment by rr-** [comment]
@Luni-4 does this work for you?

```diff
diff --git a/bubblesub/ui/main_window.py b/bubblesub/ui/main_window.py
index b36ccc5..428fbfa 100644
--- a/bubblesub/ui/main_window.py
+++ b/bubblesub/ui/main_window.py
@@ -81,9 +81,13 @@ class MainWindow(QtWidgets.QMainWindow):
 
         self.video.layout().setContentsMargins(0, 0, 2, 0)
         self.editor_splitter.setContentsMargins(2, 0, 0, 0)
-        self.main_splitter.setContentsMargins(8, 8, 8, 8)
 
-        self.setCentralWidget(self.main_splitter)
+        self.main_wrapper = QtWidgets.QWidget(self)
+        layout = QtWidgets.QHBoxLayout(self.main_wrapper)
+        layout.setContentsMargins(8, 8, 8, 8)
+        layout.addWidget(self.main_splitter)
+
+        self.setCentralWidget(self.main_wrapper)
         self.setStatusBar(self.status_bar)
 
         self.subs_grid.setFocus()
```

**Comment by Luni-4** [comment]
Fixed! Thanks a lot!
