### ISSUE TITLE
Configuration files are not removed

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#47]
When I uninstall `bubblesub` using the following command `pip uninstall bubblesub`, the configuration files contained in `$XDG_CONFIG_HOME/bubblesub/` aren't removed.

**Comment by rr-** [comment]
Can you think of anything that removes its configuration after `pip uninstall`?

I'm not talking about `pacman -Rs` or `apt-get remove`, specifically `pip uninstall`.

**Comment by rr-** [comment]
https://stackoverflow.com/questions/1550226/python-setup-py-uninstall#comment20894040_1550235

**Comment by Luni-4** [comment]
Could configuration files be added into these directory?

```
Uninstalling bubblesub-0.0:
  Would remove:
    /usr/local/bin/bubblesub
    /usr/local/lib/python3.7/dist-packages/bubblesub-0.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/bubblesub/*
Proceed (y/n)?
``` 

In this way `pip uninstall` would remove them completely without any effort.

**Comment by rr-** [comment]
No. They're not a part of the package.

**Comment by rr-** [comment]
You're confusing the role of `pip` with your OS software/package manager.

**Comment by Luni-4** [comment]
> You're confusing the role of `pip` with your OS software/package manager.

`setup.py` allows to add additional data to a package, configuration files are additional data for `bubblesub` and should be removed together with it in my opinion.  If I'm not interested in `bubblesub` anymore, why should I leave garbage data around? I guess it's pretty uncomfortable cleaning that data manually. Just my opinion. Leave it that way. but it remains uncomfortable the same.

**Comment by rr-** [comment]
Configuration files are your artifacts, not the package's. 

They're NOT related to the package. They're YOUR configuration.
