### ISSUE TITLE
Crash when zooming in/out many times

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#5]
If I run "Zoom spectogram in/out by 10%" commands many times, bubblesub crashes.

**Comment by rr-** [comment]
LMK if 00d006a fixes the issue for you.

**Comment by Luni-4** [comment]
Fixed!
Thanks!

**Comment by Luni-4** [comment]
Fix the problem when there is no data. If I run them many times on some data, it crashes

**Comment by rr-** [comment]
I need exception info then

**Comment by Luni-4** [comment]
I have a segmentation fault, no exceptions. This is the `gdb` output

`Thread 22 "SpectrumWorker" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa1941700 (LWP 11754)]
__memset_avx2_erms ()
    at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:147
147	../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S: File or directory does not exist. `

**Comment by rr-** [comment]
Most likely this is because of https://github.com/FFMS/ffms2/issues/299
Make sure you're using ffms that has this patch: https://github.com/FFMS/ffms2/commit/2d3b4fabc2c716af111271fa46dad4177ef74f3d

**Comment by Luni-4** [comment]
It works! Thanks!
