### ISSUE TITLE
Wrong view when switching between themes

### ISSUE THREAD

**Issue by Luni-4** [rr-/bubblesub#9]
To reproduce this issue:

1. Click "Switch to light color theme"
2. Again, click "Switch to light color theme"
3. Click "Switch to dark color theme"

Same if you start from the dark color theme

**Comment by rr-** [comment]
LMK if 9e0f7f4b9085fc20becc05d0d83688bfa002b2e1 fixes it for you

**Comment by Luni-4** [comment]
Fixed! Thanks!
